window.languages = {
		
	"en": {
		"startGame": "START GAME",
		"selectLevel": "SELECT LEVEL",
		"easy": "EASY",
		"medium": "MEDIUM",
		"hard": "HARD",
		"youNeed": "YOU NEED",
		"youNeed2": "POINTS",
		"points": "Points",
		"best": "Best",
		"resume": "RESUME",
		"backToMenu": "BACK TO MENU",
		"moreGames": "MORE GAMES",
		"soundOn": "SOUND ON",
		"soundOff": "SOUND OFF",
	},

	"ko": {
		"startGame": "게임 시작",
		"selectLevel": "난이도 선택",
		"easy": "쉬움",
		"medium": "보통",
		"hard": "어려움",
		"youNeed": "필요한",
		"youNeed2": "포인트",
		"points": "포인트",
		"best": "최고 점수",
		"resume": "이어하기",
		"backToMenu": "메뉴로 돌아가기",
		"moreGames": "더 많은 게임",
		"soundOn": "소리 켜기",
		"soundOff": "소리 끄기"
	},

	"pl": {
		"startGame": "ROZPOCZNIJ GRĘ",
		"selectLevel": "WYBIERZ POZIOM",
		"easy": "ŁATWY",
		"medium": "ŚREDNI",
		"hard": "TRUDNY",
		"youNeed": "POTRZEBUJESZ",
		"youNeed2": "PUNKTÓW",
		"points": "Punkty",
		"best": "Najlepszy wynik",
		"resume": "WZNÓW",
		"backToMenu": "POWRÓT DO MENU",
		"moreGames": "WIĘCEJ GIER",
		"soundOn": "DŹWIĘK WŁ.",
		"soundOff": "DŹWIĘK WYŁ."
	},
	
	
	"fr": {
		"startGame": "JOUER",
		"selectLevel": "SÉLECTIONNER NIVEAU",
		"easy": "FACILE",
		"medium": "INTERMÉDIAIRE",
		"hard": "DIFFICILE",
		"youNeed": "VOUS AVEZ BESOIN DE",
		"youNeed2": "POINTS",
		"points": "Points",
		"best": "Meilleur Score",
		"resume": "CONTINUER",
		"backToMenu": "RETOUR AU MENU",
		"moreGames": "PLUS DE JEUX",
		"soundOn": "SON ACTIVÉ",
		"soundOff": "SON DÉSACTIVÉ",
	},

	"de": {
		"startGame": "Spiel starten",
		"selectLevel": "Schwierigkeit wählen",
		"easy": "Einfach",
		"medium": "Normal",
		"hard": "Schwer",
		"youNeed": "Du benötigst",
		"youNeed2": "Punkte",
		"points": "Punkte",
		"best": "Bestwert",
		"resume": "Weiterspielen",
		"backToMenu": "Zurück zum Menü",
		"moreGames": "Mehr Spiele",
		"soundOn": "TON AN",
		"soundOff": "TON AUS",
	},

	"es": {
		"startGame": "EMPEZAR JUEGO",
		"selectLevel": "ELEGIR NIVEL",
		"easy": "FÁCIL",
		"medium": "MEDIO",
		"hard": "DIFÍCIL",
		"youNeed": "NECESITAS",
		"youNeed2": "PUNTOS",
		"points": "Puntos",
		"best": "Mejor",
		"resume": "Continuar",
		"backToMenu": "Volver al menú",
		"moreGames": "Más juegos",
		"soundOn": "SONIDO ENCENDIDO",
		"soundOff": "SONIDO APAGADO",
	},

	"it": {
		"startGame": "INIZIA PARTITA",
		"selectLevel": "SELEZIONA LIVELLO",
		"easy": "FACILE",
		"medium": "MEDIO",
		"hard": "DIFFICILE",
		"youNeed": "HAI BISOGNO DI",
		"youNeed2": "PUNTI",
		"points": "Punti",
		"best": "Record",
		"resume": "RIPRENDI",
		"backToMenu": "TORNA AL MENU",
		"moreGames": "ALTRI GIOCHI",
		"soundOn": "SUONO ACCESO",
		"soundOff": "SUONO DISATTIVATO",
	},

	"pt": {
		"startGame": "INICIAR O JOGO",
		"selectLevel": "SELECIONAR O NÍVEL",
		"easy": "FÁCIL",
		"medium": "MÉDIO",
		"hard": "DIFÍCIL",
		"youNeed": "PRECISA",
		"youNeed2": "PONTOS",
		"points": "Pontos",
		"best": "Melhor",
		"resume": "RETOMAR",
		"backToMenu": "VOLTAR AO MENU",
		"moreGames": "MAIS JOGOS",
		"soundOn": "SOM LIGADO",
		"soundOff": "SOM DESLIGADO",
	},

	"ru": {
		"startGame": "НАЧАТЬ ИГРУ",
		"selectLevel": "ВЫБОР УРОВНЯ",
		"easy": "ЛЕГКИЙ",
		"medium": "СРЕДНИЙ",
		"hard": "ТРУДНЫЙ",
		"youNeed": "ВАМ ПОТРЕБУЕТСЯ",
		"youNeed2": "ОЧКОВ",
		"points": "Очки",
		"best": "Лучшие",
		"resume": "ПРОДОЛЖИТЬ",
		"backToMenu": "НАЗАД В МЕНЮ",
		"moreGames": "ЕЩЕ ИГРЫ",
		"soundOn": "ЗВУК ВКЛЮЧЕН",
		"soundOff": "ЗВУК ВЫКЛЮЧЕН",
	},

	"tr": {
		"startGame": "OYUNU BAŞLAT",
		"selectLevel": "SEVİYE SEÇ",
		"easy": "KOLAY",
		"medium": "ORTA",
		"hard": "ZOR",
		"youNeed": "",
		"youNeed2": "PUNKTÓW",
		"points": "Puanlar",
		"best": "En İyi",
		"resume": "DEVAM",
		"backToMenu": "MENÜYE GERİ DÖN",
		"moreGames": "DAHA FAZLA OYUN",
		"soundOn": "SES AÇIK",
		"soundOff": "SESİ KAPAMAK",
	},
	
	"ja": {
		"startGame": "ゲームを開始",
		"selectLevel": "レベルを選択",
		"easy": "簡単",
		"medium": "普通",
		"hard": "難しい",
		"youNeed": "必要です",
		"youNeed2": "ポイント",
		"points": "ポイント",
		"best": "ベスト",
		"resume": "再開",
		"backToMenu": "メニューに戻る",
		"moreGames": "他のゲーム",
		"soundOn": "サウンドオン",
		"soundOff": "サウンドオフ"
	}
	

};